# Generated by Django 4.1.1 on 2022-10-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
