# Generated by Django 4.1.1 on 2022-10-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fechaNacimiento',
            new_name='fechaCreacion',
        ),
    ]
