# Generated by Django 4.1.1 on 2022-10-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0004_rename_fechanacimiento_familiar_fechacreacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fechaCreacion',
        ),
    ]
