# Generated by Django 4.1.1 on 2022-10-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0005_remove_familiar_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
