# Generated by Django 4.1.1 on 2022-10-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0007_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
