# Generated by Django 4.1.2 on 2022-10-26 18:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0008_delete_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('sub_titulo', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=30)),
                ('fechaCreacion', models.DateField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
    ]
