# Generated by Django 4.1.2 on 2022-10-28 00:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0009_blogfamiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfamiliar',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
