# Generated by Django 4.1.2 on 2022-10-28 23:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0010_alter_blogfamiliar_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfamiliar',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
