# Generated by Django 4.1.2 on 2022-11-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMVT', '0011_alter_blogfamiliar_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogfamiliar',
            old_name='sub_titulo',
            new_name='subtitulo',
        ),
    ]
